### PR TITLE
Update zhCN.lua

### PR DESCRIPTION
**Pull request by nanjuekaien1**

### CODE REVIEW

**Comment by nanjuekaien1** [comment]
@dfherr You're lazy again, don't update CN and TW

**Comment by dfherr** [comment]
@nanjuekaien1 relax ;) I had a very busy week and no time for coding. I will have a longer session today or tomorrow

**Comment by nanjuekaien1** [comment]
@dfherr Work is important. I rearranged the localized files, uploaded them and waited for your time。 ：）

**Comment by nanjuekaien1** [comment]
@dfherr  Go out to do epidemic prevention, after all, the epidemic is not over yet.

**Pull request closed without merging**
