### PR TITLE
Update zhCN.lua

### PR DESCRIPTION
**Pull request by nanjuekaien1**

### CODE REVIEW

**Comment by nanjuekaien1** [comment]
@dfherr I just got the message that the data is refreshed at the fastest rate of 1 second. Setting 0.05 seconds also refreshes in 1 second.

**Comment by dfherr** [comment]
> @dfherr I just got the message that the data is refreshed at the fastest rate of 1 second. Setting 0.05 seconds also refreshes in 1 second.

The settings affects the minimum time between two updates of the visual threat table, not of the underlying threat data. I have no influence on the underlying threat data anymore.

There are two different situations:

1. I update when I get a `UNIT_THREAT_LIST_UPDATE` event from the game (this appears to fire only once per second while you attack the same target, but might trigger more often on target switches).
2. I update and actively poll in this minimum interval when you are targeting something that I do not get updates from, e.g. when you are a healer and target a tank, I poll every x update time.

That's why it says "minimum". It's never faster, but might be slower.

**Comment by nanjuekaien1** [comment]
Take it easy. There is always a way to solve the stability of hatred

**Comment by nanjuekaien1** [comment]
Thinking of an old plugin omen, I went to find out how it works

**Comment by nanjuekaien1** [comment]
Still follow your way of thinking, it looks the same as your way of thinking。  ：）

**Pull request merged**
