### PR TITLE
Update ThreatClassic2.toc

### PR DESCRIPTION
**Pull request by nanjuekaien1**

### CODE REVIEW

**Comment by dfherr** [comment]
ah thanks. I thought I already deleted that, but apparently didn't commit it!

**Comment by nanjuekaien1** [comment]
@dfherr  ：） 

Modified, shout, I will go to a ZG test when the time is right

**Comment by nanjuekaien1** [comment]
@dfherr Check the TOC of your V2.22 release

**Comment by dfherr** [comment]
> @dfherr Check the TOC of your V2.22 release

these values are not so important. they are more meant for documentation than actually used.

**Comment by nanjuekaien1** [comment]
@dfherr Good night, hope to find new discoveries tomorrow.

**Pull request merged**
