### PR TITLE
Update zhCN.lua

### PR DESCRIPTION
**Pull request by nanjuekaien1**
You can't find this option, you can delete it.  

I made a note

### CODE REVIEW

**Comment by dfherr** [comment]
will merge before the next release. thank you :)

**Comment by dfherr** [comment]
@nanjuekaien1 I made some changes to the message `L.message_incompatible` and `L.message_outdated` to remove LibThreatClassic2 mentions.

**Comment by nanjuekaien1** [comment]
@dfherr  LibThreatClassic2Remove, does Blizzard open the hate port in advance?

**Comment by dfherr** [comment]
It's available from patch 1.13.5, which is live in US and EU since yesterday. Isn't it available in China?

**Comment by dfherr** [comment]
@nanjuekaien1 It's available from patch 1.13.5, which is live in US and EU since yesterday. Isn't it available in China?

**Comment by nanjuekaien1** [comment]
@dfherr I got up in the morning and saw you release a new version before I asked you. . . After I played the game, I found that the game was updated to 1.13.5.

**Comment by nanjuekaien1** [comment]
@dfherr  /tc2 ver  After the error

AddOns\ThreatClassic2\core\core.lua:1416: attempt to index global 'self' (a nil value)
Count: 1

Call Stack:
[C]: ?
AddOns\ThreatClassic2\core\core.lua:1416: in function `?'
FrameXML\ChatFrame.lua:4695: in function <FrameXML\ChatFrame.lua:4642>
[C]: in function `ChatEdit_ParseText'
FrameXML\ChatFrame.lua:4356: in function `ChatEdit_SendText'
FrameXML\ChatFrame.lua:4392: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

**Comment by nanjuekaien1** [comment]
Enable downscaleThreat  After looking at the list, my hatred is 60%, and the voice reminds me OT.Also, sometimes refreshing data is slow, I set 0.05 seconds to refresh, I feel out of time.Go back to your raid test.I suspect Blizzard has limited the frequency of data transmission

**Comment by dfherr** [comment]
Yes, I should change the text to `L.general_updateFreq    = "Minimum time (in seconds) between updates."`

i.e. after the time I update once blizzard gives me anything new.

**Comment by dfherr** [comment]
@nanjuekaien1 can you just give me the translation for `L.general_updateFreq = "Minimum time (in seconds) between updates."` here? I'll update a new version also with a fix to the version command.

**Comment by nanjuekaien1** [comment]
uploaded @dfherr

**Comment by nanjuekaien1** [comment]
@dfherr  Leave for two hours. Come back and follow up with your version.  ：）

**Pull request merged**
