### PR TITLE
Use targettarget unit for calculations for friendly players only.

### PR DESCRIPTION
**Pull request by kmccleary**
Fixes issue #19.

### CODE REVIEW

**Comment by dfherr** [comment]
Hi, thanks for contributing!

This would mean targeting a player pet will show aggro on the pet rather than on the pets target, which doesn't make a lot of sense.

A better fix for #19 should be to make an additional target check on entering combat. That should solve the issue right?

Also it makes probably sense to also check if targettarget is friendly and rather not show anything than aggro on a friendly unit.

**Comment by kmccleary** [comment]
Thanks for the feedback.  I had not considered the interaction with pets, as I play a priest.

I don’t think an additional check at combat entry is the best solution, but would probably work.  Would using UnitPlayerControlled(“target”) be a better choice?  Also, is player-controlled units all being friendly a safe assumption?

**Comment by dfherr** [comment]
I published version 2.09 with this fix https://github.com/dfherr/ThreatClassic2/commit/02cfa9dcb3348ef46e140e2a22b0239a685d716b

The new assumption is: If the target isn't friendly (catches neutrals) it uses that, otherwise it checks if the targettarget isn't friendly and uses that. If target and targettarget are friendly it assumes no valid target. Target checks on entering combat and on target change :)

I will test it on Monday myself. if that doesn't solve the issue, there might be a better solution. Maybe a combination of PlayerIsFriend and UnitPlayerControlled. I'm not sure what UnitPlayerControlled exactly returns true on and what not.

**Comment by dfherr** [comment]
Aw, shit. Player entering combat won't help if e.g. a warrior uses blood rage before the fight actually starts leaving Vael still friendly. And that's a very common scenario :(

Actually the best logic would probably be:

if target is not friendly, use target
else if targettarget exists and is not friendly use targettarget
else fallback to target (instead of targettarget like currently).

**Comment by kmccleary** [comment]
I think friendliness is irrelevant; we are using it as a way to determine if the unit was controlled by the player or not.  I think the following logic is more appropriate:

if target is player-controlled, use targettarget
else use target

I've updated my branch accordingly, and will give it a proper test on Tuesday worst case.

**Comment by dfherr** [comment]
if you ignore friendliness and target a hostile player, you will get his target (i.e. the targettarget) as a threat display, which is definitely not the intended behavior.

your approach is to use targettarget whenever target is a player-controlled friendly unit, which makes sense, but doesn't work for friendly npcs that help in battle. A noteworthy example is when I target an Instructor Razuvious add that's currently tanking, I won't see threat.

my approach is to use targettarget only if target is friendly and targettarget is an enemy. This will fail if a previously friendly target had an enemy in target and then becomes hostile. Is there any noteworthy example of this behavior in the game?

Both approaches should solve Vaelestraz. And both approaches fail, if a previously hostile target turns friendly.

Using my approach and updating it regularly should work in all imaginable situations. However, I'm not sure that's even worth it for the few edge cases that are also solved by changing targets. Vael is just so bad, because all dd's don't change targets.

**Comment by kmccleary** [comment]
Agreed, there are quite a few edge cases I had not considered.  I think your approach of using hostility in selecting which target to use is the correct approach, since there have been no major complaints up to this point.

I think you have correctly identified the issue being the playerTarget variable not updated frequently enough.  Being that there doesn't seem to be an event hook that quite fits this need, I've opted to err on the side of accuracy, and have moved the call to UpdatePlayerTarget into CheckStatus rather than on specific events, which should guarantee TC2.playerTarget to be correct on every update.

I'm a bit out of my element, and unfortunately not familiar enough with the WoW API's workings to know if this has any unintended side effects, but I would assume the extra calls to UnitExists and UnitIsFriend this will result in to not hit the network, and thus be relatively safe to call frequently.

I will be testing this out as I play, and will update later on if it works correctly.

**Comment by dev7355608** [comment]
Replacing the second `UnitIsFriend` with `UnitCanAssist` in `UpdatePlayerTarget` might solve the problem as well. Vael might be friendly at first, but we shouldn't be able to assist him, i.e. buff him etc.

**Comment by kmccleary** [comment]
For players that didn't change targets frequently, checking the targeting at every call of CheckStatus worked perfectly.  As a healer, I frequently change targets, and there would be times where I'd see nothing on the threat meter while swapping between targets until my client updated with the correct targeting information.  I'm guessing, but I think this is caused by the sheer number of messages getting passed during a raid and targeting is lower priority.  A more efficient approach may help this.

**Pull request closed without merging**
